In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('/content/Attrition - Attrition.csv')

In [29]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [30]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [31]:
lb = LabelEncoder()

In [32]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [33]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [34]:
df['Attrition'] = lb.fit_transform(df['Attrition'])
df['BusinessTravel'] = lb.fit_transform(df['BusinessTravel'])
df['Department'] = lb.fit_transform(df['Department'])
df['EducationField'] = lb.fit_transform(df['EducationField'])

In [35]:
oe = OrdinalEncoder(categories=[('Male','Female'),('Married','Single','Divorced')])
df_ar = oe.fit_transform(df[['Gender','MaritalStatus']])

In [37]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [38]:
df_ar2 = ohe.fit_transform(df[['Over18','OverTime']])

In [47]:
df3 = pd.get_dummies(df, columns=['JobRole'],drop_first=True)

In [48]:
df = pd.read_csv('/content/insurance - insurance.csv')

In [49]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [51]:
# df.isnull().sum()

In [53]:
categorical_features = df.select_dtypes(include='object').columns.tolist()

In [58]:
numerical_features = df.select_dtypes(include='number').columns.tolist()

In [59]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [61]:
Cat_pipeline = Pipeline(steps = [('encode',LabelEncoder()),
         'impute',SimpleImputer(strategy='most_frequent')])

num_pipeline = Pipeline(steps=[('impute',SimpleImputer(strategy='mean')),
                               'scale',StandardScaler()])

In [65]:
from sklearn.compose import ColumnTransformer

In [66]:
preprocessor = ColumnTransformer(transformers=[
    ('num',num_pipeline,numerical_features),
    ('cat',Cat_pipeline,categorical_features)
])

In [70]:
df = pd.read_csv('/content/covid_toy.csv')

In [71]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [72]:
df['gender'] = lb.fit_transform(df['gender'])
df['has_covid'] = lb.fit_transform(df['has_covid'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])

In [76]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [75]:
from sklearn.model_selection import train_test_split

In [77]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

from sklearn.preprocessing import MinMaxScaler
mn = MinMaxScaler()

In [79]:
x_train_sc = sc.fit_transform(x_train)

In [80]:
x_train_mn = mn.fit_transform(x_train)