In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/credit_scoring - credit_scoring.csv')

In [ ]:
df.head()

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771,6,957000,2.76,12,Auto Loan
3,58,Female,Married,PhD,Unemployed,0.12,1371,2,4731000,6.57,60,Auto Loan
4,32,Male,Married,Bachelor,Self-Employed,0.99,828,2,3289000,6.28,36,Personal Loan

In [ ]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [ ]:
x = df.drop(columns=['Loan Amount'])
y = df['Loan Amount']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [ ]:
x_train

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Interest Rate,Loan Term,Type of Loan
886,41,Male,Married,PhD,Self-Employed,0.37,2000,10,11.31,48,Auto Loan
488,48,Female,Married,Master,Employed,0.11,2857,1,18.35,48,Home Loan
265,54,Male,Married,High School,Self-Employed,0.02,1971,6,19.07,12,Home Loan
112,27,Female,Divorced,PhD,Unemployed,0.67,142,4,19.70,12,Personal Loan
650,63,Female,Single,High School,Employed,0.14,685,2,14.22,24,Personal Loan
...,...,...,...,...,...,...,...,...,...,...,...
289,40,Female,Married,High School,Self-Employed,0.17,1371,3,11.39,12,Auto Loan
109,62,Female,Married,Bachelor,Unemployed,0.63,85,2,5.09,48,Auto Loan
907,55,Male,Single,Master,Unemployed,0.21,771,2,6.28,60,Home Loan
480,60,Male,Single,Master,Self-Employed,0.61,1142,5,11.93,60,Auto Loan
688,51,Female,Married,Master,Employed,0.32,2000,7,10.20,48,Home Loan

In [ ]:
x_train['Type of Loan'].value_counts()

Type of Loan
Auto Loan        274
Home Loan        269
Personal Loan    257
Name: count, dtype: int64

In [ ]:
x_train.shape

(800, 11)

In [ ]:
x_test.shape

(200, 11)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female']])
x_train_gender = oe.fit_transform(x_train[['Gender']])

x_test_gender = oe.fit_transform(x_test[['Gender']])

In [ ]:
x_train_gender.shape

(800, 1)

In [ ]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

x_train_marital_education_emp = ohe.fit_transform(x_train[['Marital Status','Education Level','Employment Status']])

x_test_marital_education_emp = ohe.fit_transform(x_test[['Marital Status','Education Level','Employment Status']])

In [ ]:
x_train_marital_education_emp.shape

(800, 7)

In [ ]:
oe = OrdinalEncoder(categories=[['Auto Loan','Home Loan','Personal Loan']])
x_train_loan = oe.fit_transform(x_train[['Type of Loan']])

x_test_loan = oe.fit_transform(x_test[['Type of Loan']])

In [ ]:
x_train_loan.shape

(800, 1)

In [ ]:
x_train_num = x_train.select_dtypes(include='number').values

In [ ]:
x_test_num = x_test.select_dtypes(include='number').values

In [ ]:
x_train_transform = np.concatenate((x_train_gender,x_train_loan,x_train_marital_education_emp,x_train_num),axis=1)

In [ ]:
x_train_transform.shape

(800, 15)

COLUMN TRANSFORMER

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['Male','Female'],['Auto Loan','Personal Loan','Home Loan']]),['Gender','Type of Loan']),
    ('tnf2',OneHotEncoder(drop='first',sparse_output=False),['Marital Status','Education Level','Employment Status'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(800, 15)

In [ ]:
df = pd.read_csv('/content/insurance - insurance.csv')

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['charges']),df['charges'],test_size=0.2,random_state=50)

In [ ]:
x_train

      age     sex     bmi  children smoker     region
1048   25  female  22.515         1     no  northwest
45     55    male  37.300         0     no  southwest
201    48  female  32.230         1     no  southeast
153    42  female  23.370         0    yes  northeast
1251   19    male  19.800         0     no  southwest
...   ...     ...     ...       ...    ...        ...
229    47    male  25.460         2     no  northeast
70     27  female  24.750         0    yes  southeast
132    53  female  35.900         2     no  southwest
1313   19  female  34.700         2    yes  southwest
109    63    male  35.090         0    yes  southeast

[1070 rows x 6 columns]

In [ ]:
x_train.shape

(1070, 6)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['male','female'],['yes','no']])
x_train_sex_smoker = oe.fit_transform(x_train[['sex','smoker']])
x_test_sex_smoker = oe.fit_transform(x_test[['sex','smoker']])

In [ ]:
x_train_sex_smoker.shape

(1070, 2)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_region = ohe.fit_transform(x_train[['region']])
x_test_region = ohe.fit_transform(x_test[['region']])

In [ ]:
x_train_region.shape

(1070, 3)

In [ ]:
x_train_num = x_train.select_dtypes(include='number').values
x_test_num = x_test.select_dtypes(include='number').values

In [ ]:
x_train_num.shape

(1070, 3)

In [ ]:
x_train_transformed = np.concatenate((x_train_sex_smoker,x_train_num,x_train_region),axis=1)

In [ ]:
x_train_transformed.shape

(1070, 8)

Column Transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['male','female'],['yes','no']]),['sex','smoker']),
    ('tnf2',OneHotEncoder(drop='first',sparse_output=False),['region'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(1070, 8)